### ISSUE TITLE
打开前端就是这样，是怎么回事？

### ISSUE THREAD

**Issue by pwshanjiji** [abel-chai/music-player#8]
![屏幕截图 2023-11-17 174010](https://github.com/abel-chai/music-player/assets/149028202/e08b46b6-443a-414d-8f1c-11f7df35d171)

**Comment by abel-chai** [comment]
你前后端都运行了吗

**Comment by pwshanjiji** [comment]
运行了

**Comment by abel-chai** [comment]
你前端刷新界面，后端的控制台有什么报错信息吗

**Comment by pwshanjiji** [comment]
![屏幕截图 2023-11-17 214441](https://github.com/abel-chai/music-player/assets/149028202/d2daaadc-8b1b-4637-ab01-67e5d03f8e3f)
后端没反应

**Comment by abel-chai** [comment]
这个文件里面src\utils\request.js开头的baseURL改为baseURL = 'http://localhost:9999'，试试看

**Comment by abel-chai** [comment]
这个环境变量没有改，目前你应该是用本地的服务器

**Comment by pwshanjiji** [comment]
![image](https://github.com/abel-chai/music-player/assets/149028202/de95e6bc-e75a-4989-833b-686914a6f956)
还是这样

**Comment by abel-chai** [comment]
上面那个baseURL改成localhost:9999
默认走的是这个process.env.NODE.ENV == "development"

**Comment by abel-chai** [comment]
应该是写前端的没改这个

**Comment by abel-chai** [comment]
最上面那个baseURL的赋值没啥作用，在if哪里又重新赋值了，可能我刚才描述的不是太全面

**Comment by abel-chai** [comment]
<img width="359" alt="屏幕截图 2023-11-17 220856" src="https://github.com/abel-chai/music-player/assets/80684431/1ce7d3f7-a905-4c91-8f78-5a2f2080ca45">
这样

**Comment by pwshanjiji** [comment]
那个问题解决了但是这些静态资源加载不出来
![image](https://github.com/abel-chai/music-player/assets/149028202/7c572ed2-84b1-4825-8a88-a90e80e40cf2)

**Comment by pwshanjiji** [comment]
后端也没有报错

**Comment by abel-chai** [comment]
你后端的项目目录看一下呗

**Comment by pwshanjiji** [comment]
![image](https://github.com/abel-chai/music-player/assets/149028202/eacf4d74-bb68-46d7-bcf7-a8818cf694dd)

**Comment by pwshanjiji** [comment]
![image](https://github.com/abel-chai/music-player/assets/149028202/a02d8ae3-5abc-46f8-beeb-a21a9d7bba1f)

**Comment by abel-chai** [comment]
那个img文件夹位置有问题，等一会回宿舍给你看一下

**Comment by pwshanjiji** [comment]
嗯嗯，非常感谢

**Comment by abel-chai** [comment]
<img width="190" alt="屏幕截图 2023-11-17 224214" src="https://github.com/abel-chai/music-player/assets/80684431/4ae9f775-2878-483a-a0c8-b431554c627a">

**Comment by abel-chai** [comment]
后端项目目录，把下载的那个图片和音乐放在这里

**Comment by pwshanjiji** [comment]
在哪下载，我没找到

**Comment by abel-chai** [comment]
额，链接失效了，看看传到网盘，但是好像速度有点慢。。

**Comment by pwshanjiji** [comment]
没事啥时候都行

**Comment by abel-chai** [comment]
你现在下载呗，在那个music-player-back的readme文件里面有那个链接

**Comment by pwshanjiji** [comment]
好的

**Comment by pwshanjiji** [comment]
![image](https://github.com/abel-chai/music-player/assets/149028202/b9a7e317-a725-4676-9e5e-7b662f6df80a)
![image](https://github.com/abel-chai/music-player/assets/149028202/b6a64df7-0b49-4e97-943b-8e920241e4c9)
添加完之后是这样的

**Comment by abel-chai** [comment]
请求之后后端报的啥信息

**Comment by pwshanjiji** [comment]
![image](https://github.com/abel-chai/music-player/assets/149028202/ef5f38d1-87a9-44d0-a469-4d28bcd3e7c5)
后端没啥

**Comment by pwshanjiji** [comment]
![image](https://github.com/abel-chai/music-player/assets/149028202/aac5bc6c-9087-43ab-b436-90fc5ea99300)
但是登录后会报错

**Comment by abel-chai** [comment]
你会用postman嘛，发几个请求给后端，看后端可正常响应

**Comment by abel-chai** [comment]
还有你的redis开了吧

**Comment by abel-chai** [comment]
数据库配置文件改你自己的用户名密码啥的

**Comment by pwshanjiji** [comment]
数据库和redis没问题，postman没用过

**Comment by pwshanjiji** [comment]
数据库和redis没啥问题

**Comment by pwshanjiji** [comment]
![image](https://github.com/abel-chai/music-player/assets/149028202/f01517db-6230-44c1-8ac4-52e3ec56eed9)
![image](https://github.com/abel-chai/music-player/assets/149028202/38f8049c-4121-46e0-badd-c7c97c6415f1)
这样吗

**Comment by pwshanjiji** [comment]
![image](https://github.com/abel-chai/music-player/assets/149028202/dc78c95b-a025-40c5-bdca-0154760aa7b0)

**Comment by abel-chai** [comment]
你后端服务器的端口不是9999嘛

**Comment by pwshanjiji** [comment]
要测9999吗

**Comment by abel-chai** [comment]
application.ymal文件，你截一下你的
![Uploading 1.png…]()

**Comment by pwshanjiji** [comment]
![image](https://github.com/abel-chai/music-player/assets/149028202/dfc3b8e5-a196-43e6-ae5d-87538d3b40ea)

**Comment by pwshanjiji** [comment]
![image](https://github.com/abel-chai/music-player/assets/149028202/e13be1e6-ef2a-4cda-92f8-f4953369bc87)

**Comment by pwshanjiji** [comment]
这东西没啥解决办法吗
![image](https://github.com/abel-chai/music-player/assets/149028202/deeb3427-dca1-4b9a-a9ef-504343b332fb)

**Comment by abel-chai** [comment]
你后端开着，然后浏览器请求一下这个地址http://localhost:9999/img/bannerImg/1.jpg，看一下出不出来页面，以及后端有没有报错
